language: java

dist: xenial

services:
  - docker

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build -t java-app .
  - docker images
  - docker tag java-app $DOCKER_USERNAME/java-app
  - docker push $DOCKER_USERNAME/java-app

if: type = pull_request OR branch = main OR tag IS present

  deploy:
  - provider: script
    skip_cleanup: true
    script: echo "DONE!"
    on:
      branch: main