language: java

# dist: xenial

# services:
#   - docker

# if: type = pull_request OR branch = master OR tag IS present
# if: tag IS present

script: mvn package -DskipTests

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t ci-be .
  - docker images
  - docker tag ci-be $DOCKER_USERNAME/ci-be
  - docker push $DOCKER_USERNAME/ci-be

deploy:
  - provider: script
    skip_existing: true
    skip_cleanup: true
    script: echo "DONE!"
    on:
      tags: true